### ISSUE TITLE
A token of appreciation

### ISSUE THREAD

**Issue by tanishqkc** [Defcon27/Machine-Learning#1]
Hey bro! I read your registration for our club VinnovateIT and browsed through your GitHub. The amount of work you have done is just amazing! Keep up the hard work! All the best for the upcoming rounds of the registration. We would love to have you on board with us!
Do browse through our GitHub page (https://github.com/vinnovateit/) and tell us if u find something interesting!

**Comment by Defcon27** [comment]
Thank You 😄
